My Capstone Project
lincoln1883/mod1-capstone-project pull request #1
Opened 2023-04-19 23:00 UTC by lincoln1883

Milestone 0 - 2, I created the repo and cloned it to my local machine where I:
- Add linters and packages.
- Add assets, images and icons.
- Add boilerplate HTML and CSS.
- Add layout for mobile-first development.
- Add Layout and styles for the intro section.
- Add layout and styling for the events section.
- Add layout and styles for the sponsor's section and add more images.
- Add layout and styles for the footer section.
- Add about page skeleton and edited the page title and footer.
- Add a logo detail and history section to the About page.
- Fix linter errors, pushed and deployed the website.
Milestone 3 + 4, I created a new branch for the Desktop version where I:
- Add layout and styling for the main navigation.
- Adjusted the layout and add styling to the intro section.
- Edited the content and added styling to the feature section.
- Add layout and styling for the sponsors and footer section.
- Add layout and styling for the Top navbar to hold social links and more.
- Add layout and styling to the About page.
- Add interactivity to the website with animations, transitions and links.
- Fixed errors and pushed changes.
Milestone 5 + 6, I created a new branch for the javascript where I:
- Removed the hard-code HTML and dynamically generated the feature section for javascript DOM elements.
- Add documentation for the project including a video describing my work including the challenges.
Milestone 6, Deployment of the website can be viewed here:[Live view](https://lincoln1883.github.io/mod1-capstone-project/)

2023-04-19 23:53 UTC, zieeco requested changes
Hi @lincoln1883,


<img height="230" src="https://media0.giphy.com/media/bGCwmLDnwL25kCg3FV/giphy-downsized-medium.gif"/>

Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️
- Good commit messages :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 23:53 UTC, zieeco commented on style.css
> +}
- Hey, for the mobile version, to improve the user experience, let's reduce the font size to 0.75rem as the text content's length is too long compared to the original design.

2023-04-19 23:53 UTC, zieeco commented on style.css
> +}
- Hey, for the desktop version, let's increase the padding to 3rem 9rem to improve our design to be close to the design template and to improve the user experience on the desktop version.




*design*
![Screenshot from 2023-04-20 00-12-16](https://user-images.githubusercontent.com/59397159/233219774-7012ac63-84c3-4028-ac02-2333eff01569.png)

*your design*
![Screenshot from 2023-04-20 00-10-52](https://user-images.githubusercontent.com/59397159/233219777-f69c7236-90c4-4858-bae7-3f9d3ec33a61.png)

2023-04-19 23:53 UTC, zieeco commented on style.css
> +  }
- Hey, on the desktop version, let's align the text to the center to make it close to the original design.
- let's also add the missing white border on each card.

*design*
![Screenshot from 2023-04-20 00-21-40](https://user-images.githubusercontent.com/59397159/233220391-842b23e3-e893-40fc-832d-493e7c6ec922.png)

*your design*
![Screenshot from 2023-04-20 00-25-35](https://user-images.githubusercontent.com/59397159/233220656-8a4c3cb0-5f9d-438f-b3fd-f769827b5d40.png)

2023-04-19 23:53 UTC, zieeco commented on style.css
> +}
- Hey, let's add a filter effect on these images to be close to the original design. you can add this  
` filter: grayscale(100%) contrast(30%);`. You can play around with the contrast to adjust it.

2023-04-19 23:53 UTC, zieeco commented on index.html
> +				<a href="#"><img class="logo" src="./assets/logos/logo-nav.png" alt="logo"></a>
- Hey, please, kindly make the logo link to the homepage by making it a live link to the index.html page and not a dead link.

2023-04-19 23:53 UTC, zieeco commented on README.md
> +- [Video Presentation](https://www.loom.com/share/59480bb95ab344d19bee283cd3fee8a4)
- Hey, the video's maximum length should not exceed 5 mins. kindly record another video to ensure you've all the requirements for the video. you can check the project requirement for more details on the video.

2023-04-19 23:53 UTC, zieeco commented on index.html
> +					<img src="./assets/images/jtb-logo.jpg" alt=""></li>
### ADD ALTERNATIVE TEXT TO ALL YOUR IMAGES WITHOUT ANY 

- Hey, let's add an alternative text to ALL THE IMAGES without the alt text in the HOME and ABOUT PAGE  to improve the web accessibility of your webpage.

2023-04-20 15:53 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 16:00 UTC, merged